import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { pesqueiros, especiesTemporada, iscas, config } from './schema'
import { DEFAULT_WEIGHTS } from '@/engine/constants'

// ──────────────────────────────────────────────
// Seed data arrays (exported for tests)
// ──────────────────────────────────────────────

export const SEED_PESQUEIROS = [
  {
    slug: 'ilha-dos-currais',
    nome: 'Ilha dos Currais',
    lat: -25.4420,
    lon: -48.3580,
    tipo: 'laje',
    profundidadeM: 18,
    distanciaCostaMn: 8,
    especiesAlvo: ['vermelho', 'garoupa', 'badejo', 'cioba'],
    ativo: true,
  },
  {
    slug: 'naufragio-do-tocoyo',
    nome: 'Naufrágio do Tocoyo',
    lat: -25.5300,
    lon: -48.2000,
    tipo: 'naufragio',
    profundidadeM: 22,
    distanciaCostaMn: 12,
    especiesAlvo: ['garoupa', 'badejo', 'anchova'],
    ativo: true,
  },
  {
    slug: 'parcel-da-galheta',
    nome: 'Parcel da Galheta',
    lat: -25.5700,
    lon: -48.2900,
    tipo: 'parcel',
    profundidadeM: 15,
    distanciaCostaMn: 5,
    especiesAlvo: ['robalo', 'sargo', 'vermelho'],
    ativo: true,
  },
  {
    slug: 'cascalho-dos-30',
    nome: 'Cascalho dos 30',
    lat: -25.6800,
    lon: -48.0500,
    tipo: 'cascalho',
    profundidadeM: 30,
    distanciaCostaMn: 20,
    especiesAlvo: ['vermelho', 'cioba', 'dourado'],
    ativo: true,
  },
  {
    slug: 'naufragio-dos-saveiros',
    nome: 'Naufrágio dos Saveiros',
    lat: -25.4700,
    lon: -48.1900,
    tipo: 'naufragio',
    profundidadeM: 25,
    distanciaCostaMn: 15,
    especiesAlvo: ['garoupa', 'badejo'],
    ativo: false,
  },
  {
    slug: 'fundeadouro-alfa-navios',
    nome: 'Fundeadouro Alfa Navios',
    lat: -25.6500,
    lon: -48.2800,
    tipo: 'fundeadouro',
    profundidadeM: 16,
    distanciaCostaMn: 6,
    especiesAlvo: ['vermelho', 'garoupa', 'robalo', 'anchova'],
    ativo: true,
  },
  {
    slug: 'fundeadouro-bravo-navios',
    nome: 'Fundeadouro Bravo Navios',
    lat: -25.7000,
    lon: -48.2500,
    tipo: 'fundeadouro',
    profundidadeM: 18,
    distanciaCostaMn: 10,
    especiesAlvo: ['vermelho', 'garoupa', 'dourado'],
    ativo: true,
  },
  {
    slug: 'barra-da-galheta-canal',
    nome: 'Barra da Galheta Canal',
    lat: -25.5780,
    lon: -48.3200,
    tipo: 'canal',
    profundidadeM: 14,
    distanciaCostaMn: 2,
    especiesAlvo: ['robalo', 'tainha', 'carapeba', 'sargo'],
    ativo: true,
  },
  {
    slug: 'ilha-do-mel-fortaleza',
    nome: 'Ilha do Mel Fortaleza',
    lat: -25.4970,
    lon: -48.3020,
    tipo: 'baia',
    profundidadeM: 8,
    distanciaCostaMn: 1,
    especiesAlvo: ['robalo', 'tainha', 'parati', 'carapeba'],
    ativo: true,
  },
  {
    slug: 'ilha-das-pecas',
    nome: 'Ilha das Peças',
    lat: -25.4350,
    lon: -48.3500,
    tipo: 'baia',
    profundidadeM: 6,
    distanciaCostaMn: 1,
    especiesAlvo: ['robalo', 'tainha', 'parati'],
    ativo: true,
  },
  {
    slug: 'ponta-do-poco',
    nome: 'Ponta do Poço',
    lat: -25.5490,
    lon: -48.3870,
    tipo: 'baia',
    profundidadeM: 10,
    distanciaCostaMn: 0.5,
    especiesAlvo: ['robalo', 'carapeba', 'sargo', 'badejo'],
    ativo: true,
  },
  {
    slug: 'ilha-da-cotinga',
    nome: 'Ilha da Cotinga',
    lat: -25.4950,
    lon: -48.4050,
    tipo: 'baia',
    profundidadeM: 5,
    distanciaCostaMn: 0.5,
    especiesAlvo: ['robalo', 'tainha', 'parati'],
    ativo: true,
  },
  {
    slug: 'barra-de-guaratuba',
    nome: 'Barra de Guaratuba',
    lat: -25.8830,
    lon: -48.5750,
    tipo: 'canal',
    profundidadeM: 8,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'tainha', 'corvina', 'caranha'],
    ativo: true,
  },
  {
    slug: 'matinhos-offshore',
    nome: 'Matinhos Offshore',
    lat: -25.7500,
    lon: -48.3500,
    tipo: 'offshore',
    profundidadeM: 20,
    distanciaCostaMn: 5,
    especiesAlvo: ['anchova', 'dourado', 'bonito'],
    ativo: true,
  },
  {
    slug: 'barra-do-superagui',
    nome: 'Barra do Superagui',
    lat: -25.2850,
    lon: -48.1850,
    tipo: 'baia',
    profundidadeM: 6,
    distanciaCostaMn: 1,
    especiesAlvo: ['robalo', 'carapeba', 'tainha'],
    ativo: true,
  },
  // ── Naufrágios ──
  {
    slug: 'naufragio-do-rebocador',
    nome: 'Naufrágio do Rebocador',
    lat: -25.6000,
    lon: -48.1700,
    tipo: 'naufragio',
    profundidadeM: 20,
    distanciaCostaMn: 12,
    especiesAlvo: ['garoupa', 'badejo', 'pargo'],
    notas: 'Rebocador afundado, estrutura relativamente intacta',
    ativo: true,
  },
  {
    slug: 'naufragio-do-vapor',
    nome: 'Naufrágio do Vapor',
    lat: -25.5000,
    lon: -48.2300,
    tipo: 'naufragio',
    profundidadeM: 18,
    distanciaCostaMn: 8,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'sargo'],
    notas: 'Restos de embarcação antiga próximo à saída do canal da Galheta',
    ativo: true,
  },
  {
    slug: 'naufragio-dos-25m',
    nome: 'Naufrágio dos 25 metros',
    lat: -25.6500,
    lon: -48.1300,
    tipo: 'naufragio',
    profundidadeM: 25,
    distanciaCostaMn: 15,
    especiesAlvo: ['pargo', 'garoupa', 'cherne'],
    notas: 'Conhecido entre pescadores de Matinhos e Guaratuba',
    ativo: true,
  },
  {
    slug: 'naufragio-do-aco',
    nome: 'Naufrágio do Aço',
    lat: -25.7400,
    lon: -48.3800,
    tipo: 'naufragio',
    profundidadeM: 13,
    distanciaCostaMn: 5,
    especiesAlvo: ['badejo', 'sargo', 'robalo'],
    notas: 'Barcaça de aço afundada ao largo de Matinhos',
    ativo: true,
  },
  // ── Parcéis e Lajes ──
  {
    slug: 'parcel-do-boi',
    nome: 'Parcel do Boi',
    lat: -25.5100,
    lon: -48.2600,
    tipo: 'parcel',
    profundidadeM: 16,
    distanciaCostaMn: 8,
    especiesAlvo: ['garoupa', 'badejo', 'sargo', 'olhete'],
    notas: 'Formação rochosa submersa entre Galheta e Currais',
    ativo: true,
  },
  {
    slug: 'parcel-das-palmas',
    nome: 'Parcel das Palmas',
    lat: -25.4800,
    lon: -48.2800,
    tipo: 'parcel',
    profundidadeM: 14,
    distanciaCostaMn: 7,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'anchova'],
    notas: 'Próximo à Ilha das Palmas na saída da baía',
    ativo: true,
  },
  {
    slug: 'laje-do-bigua',
    nome: 'Laje do Biguá',
    lat: -25.4300,
    lon: -48.3200,
    tipo: 'laje',
    profundidadeM: 10,
    distanciaCostaMn: 3,
    especiesAlvo: ['sargo', 'badejo', 'robalo', 'pescada'],
    notas: 'Formação rochosa rasa próxima à Ilha do Mel',
    ativo: true,
  },
  {
    slug: 'parcel-de-itacolomi',
    nome: 'Parcel de Itacolomi',
    lat: -25.7600,
    lon: -48.3800,
    tipo: 'parcel',
    profundidadeM: 17,
    distanciaCostaMn: 8,
    especiesAlvo: ['garoupa', 'pargo', 'anchova'],
    notas: 'Referência antiga dos pescadores de Matinhos/Caiobá',
    ativo: true,
  },
  {
    slug: 'pedras-do-guaraguacu',
    nome: 'Pedras do Guaraguaçu',
    lat: -25.5600,
    lon: -48.4200,
    tipo: 'pedra',
    profundidadeM: 5,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'pescada', 'sargo'],
    notas: 'Pedras submersas na entrada do rio Guaraguaçu, dentro da baía',
    ativo: true,
  },
  {
    slug: 'laje-da-palangana',
    nome: 'Laje da Palangana',
    lat: -25.5600,
    lon: -48.2000,
    tipo: 'laje',
    profundidadeM: 18,
    distanciaCostaMn: 10,
    especiesAlvo: ['garoupa', 'pargo', 'cherne'],
    notas: 'Laje submersa entre Currais e a costa',
    ativo: true,
  },
  {
    slug: 'parcel-do-meio',
    nome: 'Parcel do Meio',
    lat: -25.5400,
    lon: -48.2700,
    tipo: 'parcel',
    profundidadeM: 13,
    distanciaCostaMn: 6,
    especiesAlvo: ['garoupa', 'olhete', 'sargo', 'anchova'],
    notas: 'Conhecido dos chartereiros de Pontal',
    ativo: true,
  },
  // ── Baía ──
  {
    slug: 'ponta-da-pita',
    nome: 'Ponta da Pita',
    lat: -25.5200,
    lon: -48.3250,
    tipo: 'baia',
    profundidadeM: 6,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'pescada', 'tainha', 'parati'],
    notas: 'Ponta rochosa na Ilha do Mel, lado da baía, boa de robalo na maré',
    ativo: true,
  },
  {
    slug: 'canal-do-dnos',
    nome: 'Canal do DNOS',
    lat: -25.5900,
    lon: -48.4550,
    tipo: 'canal',
    profundidadeM: 3,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'carapeba', 'baiacu', 'tainha'],
    notas: 'Canal artificial em Pontal do Paraná, pesca de light tackle e fly',
    ativo: true,
  },
  {
    slug: 'baixio-do-perigo',
    nome: 'Baixio do Perigo',
    lat: -25.4700,
    lon: -48.4200,
    tipo: 'baia',
    profundidadeM: 3,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'pescada', 'linguado'],
    notas: 'Banco de areia na baía com canais laterais produtivos',
    ativo: true,
  },
  {
    slug: 'ponta-oeste-ilha-do-mel',
    nome: 'Ponta Oeste Ilha do Mel',
    lat: -25.5520,
    lon: -48.3380,
    tipo: 'baia',
    profundidadeM: 7,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'pescada', 'sargo', 'betara'],
    notas: 'Costão rochoso na ponta oeste, transição baía/mar aberto',
    ativo: true,
  },
  {
    slug: 'enseada-do-benito',
    nome: 'Enseada do Benito',
    lat: -25.4100,
    lon: -48.3600,
    tipo: 'baia',
    profundidadeM: 5,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'carapeba', 'tainha', 'pescada'],
    notas: 'Enseada protegida boa pra robalo no inverno',
    ativo: true,
  },
  {
    slug: 'furo-do-rio-medeiros',
    nome: 'Furo do Rio Medeiros',
    lat: -25.3650,
    lon: -48.3800,
    tipo: 'baia',
    profundidadeM: 3,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'carapeba', 'pescada-amarela'],
    notas: 'Região de mangue, pesca artesanal de robalo muito produtiva',
    ativo: true,
  },
  {
    slug: 'canal-do-varadouro',
    nome: 'Canal do Varadouro',
    lat: -25.8500,
    lon: -48.5300,
    tipo: 'canal',
    profundidadeM: 5,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'pescada', 'tainha', 'parati'],
    notas: 'Canal entre Guaratuba e Caiobá, bom de robalo na virada da maré',
    ativo: true,
  },
  // ── Offshore / Pesado ──
  {
    slug: 'cascalho-dos-40',
    nome: 'Cascalho dos 40',
    lat: -25.7200,
    lon: -47.9500,
    tipo: 'cascalho',
    profundidadeM: 40,
    distanciaCostaMn: 25,
    especiesAlvo: ['pargo', 'cherne', 'namorado', 'batata'],
    notas: 'Fundo de cascalho, pesca de fundo pesada, precisa bom tempo',
    ativo: true,
  },
  {
    slug: 'pesqueiro-dos-50',
    nome: 'Pesqueiro dos 50',
    lat: -25.6300,
    lon: -47.9000,
    tipo: 'offshore',
    profundidadeM: 50,
    distanciaCostaMn: 30,
    especiesAlvo: ['pargo', 'cherne', 'namorado'],
    notas: 'Área de fundo duro profunda, peixes grandes de profundidade',
    ativo: true,
  },
  {
    slug: 'laje-dos-35',
    nome: 'Laje dos 35',
    lat: -25.8000,
    lon: -48.3200,
    tipo: 'laje',
    profundidadeM: 35,
    distanciaCostaMn: 18,
    especiesAlvo: ['garoupa', 'cherne', 'pargo', 'olhete'],
    notas: 'Formação de laje ao largo de Guaratuba, bom de garoupa grande',
    ativo: true,
  },
  {
    slug: 'pesqueiro-do-dourado',
    nome: 'Pesqueiro do Dourado',
    lat: -25.5800,
    lon: -48.0200,
    tipo: 'offshore',
    profundidadeM: 35,
    distanciaCostaMn: 20,
    especiesAlvo: ['dourado', 'bonito', 'anchova', 'olho-de-boi'],
    notas: 'Área de convergência de correntes, corrico no verão, dourado out-mar',
    ativo: true,
  },
  {
    slug: 'cascalho-do-sul',
    nome: 'Cascalho do Sul',
    lat: -25.8800,
    lon: -48.1200,
    tipo: 'cascalho',
    profundidadeM: 32,
    distanciaCostaMn: 18,
    especiesAlvo: ['pargo', 'namorado', 'batata', 'cherne'],
    notas: 'Fundo de cascalho/concheiro ao sul, divisa com SC',
    ativo: true,
  },
  // ── Região Cananéia / Ilha da Figueira / Bom Abrigo ──
  {
    slug: 'ilha-da-figueira',
    nome: 'Ilha da Figueira',
    lat: -25.0200,
    lon: -47.9200,
    tipo: 'laje',
    profundidadeM: 12,
    distanciaCostaMn: 3,
    especiesAlvo: ['garoupa', 'badejo', 'sargo', 'olhete'],
    notas: 'Ilha com costão rochoso, boa pra pesca de fundo e meia-água',
    ativo: true,
  },
  {
    slug: 'ilha-do-bom-abrigo',
    nome: 'Ilha do Bom Abrigo',
    lat: -25.1200,
    lon: -47.8600,
    tipo: 'laje',
    profundidadeM: 15,
    distanciaCostaMn: 6,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'anchova', 'vermelho'],
    notas: 'Ilha oceânica com águas claras, excelente pra mergulho e pesca',
    ativo: true,
  },
  {
    slug: 'laje-do-bom-abrigo',
    nome: 'Laje do Bom Abrigo',
    lat: -25.1400,
    lon: -47.8300,
    tipo: 'laje',
    profundidadeM: 18,
    distanciaCostaMn: 8,
    especiesAlvo: ['garoupa', 'cherne', 'pargo', 'badejo'],
    notas: 'Laje submersa ao largo da Ilha do Bom Abrigo, peixes grandes de fundo',
    ativo: true,
  },
  {
    slug: 'barra-de-cananeia',
    nome: 'Barra de Cananéia',
    lat: -25.0550,
    lon: -47.9100,
    tipo: 'canal',
    profundidadeM: 8,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'carapeba', 'tainha', 'pescada', 'corvina'],
    notas: 'Entrada do estuário de Cananéia, forte correnteza na maré, robalo na virada',
    ativo: true,
  },
  {
    slug: 'estuario-cananeia',
    nome: 'Estuário de Cananéia',
    lat: -25.0100,
    lon: -47.9300,
    tipo: 'baia',
    profundidadeM: 5,
    distanciaCostaMn: 0,
    especiesAlvo: ['robalo', 'carapeba', 'pescada-amarela', 'linguado'],
    notas: 'Estuário com mangue, um dos melhores locais de robalo do sudeste',
    ativo: true,
  },
  {
    slug: 'ilha-do-cardoso',
    nome: 'Ilha do Cardoso',
    lat: -25.1000,
    lon: -47.9600,
    tipo: 'baia',
    profundidadeM: 6,
    distanciaCostaMn: 1,
    especiesAlvo: ['robalo', 'carapeba', 'tainha', 'parati'],
    notas: 'Costa protegida da Ilha do Cardoso, pesca de robalo nos canais',
    ativo: true,
  },
  {
    slug: 'parcel-de-cananeia',
    nome: 'Parcel de Cananéia',
    lat: -25.0800,
    lon: -47.8000,
    tipo: 'parcel',
    profundidadeM: 20,
    distanciaCostaMn: 10,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'anchova', 'dourado'],
    notas: 'Formação rochosa ao largo de Cananéia, pesca embarcada de fundo e corrico',
    ativo: true,
  },
  {
    slug: 'offshore-cananeia',
    nome: 'Offshore Cananéia',
    lat: -25.0500,
    lon: -47.7000,
    tipo: 'offshore',
    profundidadeM: 35,
    distanciaCostaMn: 18,
    especiesAlvo: ['dourado', 'bonito', 'anchova', 'olho-de-boi'],
    notas: 'Área de corrico ao largo de Cananéia, dourado no verão',
    ativo: true,
  },
  {
    slug: 'ilha-de-castilho',
    nome: 'Ilha de Castilho',
    lat: -25.2600,
    lon: -47.9500,
    tipo: 'laje',
    profundidadeM: 15,
    distanciaCostaMn: 8,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'sargo', 'vermelho'],
    notas: 'Ilha rochosa com costão produtivo, pesca de fundo e meia-água. Pesqueiro favorito do Vilmar.',
    ativo: true,
  },
  {
    slug: 'laje-de-castilho',
    nome: 'Laje de Castilho',
    lat: -25.2750,
    lon: -47.9300,
    tipo: 'laje',
    profundidadeM: 20,
    distanciaCostaMn: 10,
    especiesAlvo: ['garoupa', 'cherne', 'pargo', 'badejo'],
    notas: 'Laje submersa ao redor da Ilha de Castilho, peixes de fundo grandes',
    ativo: true,
  },
  {
    slug: 'costao-castilho-norte',
    nome: 'Costão Norte Castilho',
    lat: -25.2500,
    lon: -47.9550,
    tipo: 'pedra',
    profundidadeM: 8,
    distanciaCostaMn: 8,
    especiesAlvo: ['robalo', 'sargo', 'badejo', 'olhete'],
    notas: 'Costão norte da Ilha de Castilho, robalo e sargo na pedra',
    ativo: true,
  },
  {
    slug: 'figueira-costao-sul',
    nome: 'Costão Sul Figueira',
    lat: -25.0280,
    lon: -47.9150,
    tipo: 'pedra',
    profundidadeM: 10,
    distanciaCostaMn: 3,
    especiesAlvo: ['garoupa', 'badejo', 'sargo', 'robalo'],
    notas: 'Costão sul da Ilha da Figueira, ponto produtivo do Vilmar',
    ativo: true,
  },
  {
    slug: 'figueira-laje-externa',
    nome: 'Laje Externa Figueira',
    lat: -25.0350,
    lon: -47.9000,
    tipo: 'laje',
    profundidadeM: 16,
    distanciaCostaMn: 5,
    especiesAlvo: ['garoupa', 'badejo', 'olhete', 'anchova'],
    notas: 'Laje submersa ao largo da Figueira, pesca de fundo e jigging',
    ativo: true,
  },
  // ── Estruturas ──
  {
    slug: 'boias-do-canal',
    nome: 'Bóias do Canal',
    lat: -25.5850,
    lon: -48.3050,
    tipo: 'canal',
    profundidadeM: 14,
    distanciaCostaMn: 4,
    especiesAlvo: ['anchova', 'pescada', 'corvina'],
    notas: 'Pesca junto às bóias de sinalização do canal, boa de noite',
    ativo: true,
  },
]

export const SEED_ESPECIES = [
  {
    especie: 'vermelho',
    mesesAtivos: [3, 4, 5, 6, 7, 8],
    tempAguaMin: 20,
    tempAguaMax: 26,
    luaPreferida: 'cheia',
    tiposPesqueiro: ['laje', 'naufragio', 'fundeadouro', 'cascalho'],
    iscas: ['sardinha inteira', 'lula', 'camarão morto'],
    tecnica: 'fundo',
    notas: null,
  },
  {
    especie: 'robalo',
    mesesAtivos: [3, 4, 5, 6, 7, 8, 9],
    tempAguaMin: 18,
    tempAguaMax: 28,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['baia', 'canal', 'parcel'],
    iscas: ['camarão vivo', 'corrupto', 'jig head'],
    tecnica: 'meia-água',
    notas: null,
  },
  {
    especie: 'garoupa',
    mesesAtivos: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tempAguaMin: 19,
    tempAguaMax: 27,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['naufragio', 'fundeadouro', 'laje'],
    iscas: ['sardinha', 'lula inteira', 'peixe vivo'],
    tecnica: 'fundo próximo a estrutura',
    notas: null,
  },
  {
    especie: 'tainha',
    mesesAtivos: [4, 5, 6, 7],
    tempAguaMin: 16,
    tempAguaMax: 24,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['baia', 'canal'],
    iscas: ['engodo', 'anzol com miçanga'],
    tecnica: 'superfície/meia-água',
    notas: null,
  },
  {
    especie: 'anchova',
    mesesAtivos: [4, 5, 6, 7, 8],
    tempAguaMin: 18,
    tempAguaMax: 24,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['offshore', 'parcel'],
    iscas: ['sardinha viva', 'colher', 'jig metálico'],
    tecnica: 'corrico ou jigging',
    notas: null,
  },
  {
    especie: 'dourado',
    mesesAtivos: [10, 11, 12, 1, 2, 3],
    tempAguaMin: 22,
    tempAguaMax: 28,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['offshore', 'cascalho', 'fundeadouro'],
    iscas: ['peixe vivo', 'lula', 'rapala'],
    tecnica: 'corrico de superfície',
    notas: null,
  },
  {
    especie: 'badejo',
    mesesAtivos: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tempAguaMin: 19,
    tempAguaMax: 26,
    luaPreferida: 'cheia',
    tiposPesqueiro: ['naufragio', 'laje', 'fundeadouro'],
    iscas: ['sardinha', 'lula', 'camarão'],
    tecnica: 'fundo',
    notas: null,
  },
  {
    especie: 'carapeba',
    mesesAtivos: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tempAguaMin: 18,
    tempAguaMax: 28,
    luaPreferida: 'qualquer',
    tiposPesqueiro: ['baia', 'canal'],
    iscas: ['camarão vivo', 'corrupto'],
    tecnica: 'fundo leve ou meia-água',
    notas: null,
  },
]

export const SEED_ISCAS = [
  {
    nome: 'sardinha inteira',
    tipo: 'natural',
    especiesAlvo: ['vermelho', 'garoupa', 'badejo', 'anchova'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'camarão vivo',
    tipo: 'natural',
    especiesAlvo: ['robalo', 'carapeba', 'sargo'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'lula inteira',
    tipo: 'natural',
    especiesAlvo: ['garoupa', 'vermelho', 'badejo'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'corrupto',
    tipo: 'natural',
    especiesAlvo: ['robalo', 'carapeba', 'parati'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'peixe vivo',
    tipo: 'natural',
    especiesAlvo: ['garoupa', 'dourado'],
    condicoesIdeais: 'água clara',
    disponibilidade: null,
  },
  {
    nome: 'jig head + soft bait',
    tipo: 'artificial',
    especiesAlvo: ['robalo', 'carapeba'],
    condicoesIdeais: 'corrente moderada',
    disponibilidade: null,
  },
  {
    nome: 'jig metálico',
    tipo: 'artificial',
    especiesAlvo: ['anchova', 'dourado', 'bonito'],
    condicoesIdeais: 'cardume na superfície',
    disponibilidade: null,
  },
  {
    nome: 'colher',
    tipo: 'artificial',
    especiesAlvo: ['anchova', 'dourado'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'camarão morto',
    tipo: 'natural',
    especiesAlvo: ['vermelho', 'sargo'],
    condicoesIdeais: null,
    disponibilidade: null,
  },
  {
    nome: 'engodo farinha+sardinha',
    tipo: 'natural',
    especiesAlvo: ['tainha'],
    condicoesIdeais: 'água calma',
    disponibilidade: 'inverno',
  },
]

// ──────────────────────────────────────────────
// Seed function
// ──────────────────────────────────────────────

async function seed() {
  const DATABASE_URL = process.env.DATABASE_URL || './data/pesca.db'
  const sqlite = new Database(DATABASE_URL)
  sqlite.pragma('journal_mode = WAL')
  sqlite.pragma('foreign_keys = ON')
  const db = drizzle(sqlite)

  console.log('Seeding pesqueiros...')
  for (const p of SEED_PESQUEIROS) {
    await db.insert(pesqueiros).values(p).onConflictDoNothing()
  }
  console.log(`  Inserted ${SEED_PESQUEIROS.length} pesqueiros`)

  console.log('Seeding espécies...')
  for (const e of SEED_ESPECIES) {
    await db.insert(especiesTemporada).values(e).onConflictDoNothing()
  }
  console.log(`  Inserted ${SEED_ESPECIES.length} espécies`)

  console.log('Seeding iscas...')
  for (const i of SEED_ISCAS) {
    await db.insert(iscas).values(i).onConflictDoNothing()
  }
  console.log(`  Inserted ${SEED_ISCAS.length} iscas`)

  console.log('Seeding config pesos...')
  await db
    .insert(config)
    .values({ chave: 'pesos', valor: DEFAULT_WEIGHTS })
    .onConflictDoNothing()
  console.log('  Inserted config pesos')

  sqlite.close()
  console.log('Seed complete.')
}

// Only run seed when executed directly (not when imported in tests)
const isMain = process.argv[1]?.includes('seed')
if (isMain) {
  seed().catch((err) => {
    console.error('Seed failed:', err)
    process.exit(1)
  })
}
